Import NumPy as np

In [17]:
import numpy as np

1.Create an array of 10 zeros

In [18]:
zeros_arr = np.zeros(10)

In [19]:
print(zeros_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2.Create an array of 10 fives

In [20]:
fives_array = np.full(10, 5)

In [21]:
print(fives_array)

[5 5 5 5 5 5 5 5 5 5]


3.Create an array of the integers from 10 to 50

In [22]:
integers_arr = np.arange(10, 51)

In [23]:
print(integers_arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


4.Create an array of all the even integers from 10 to 50

In [24]:
even_arr = np.arange(10, 51, 2)

In [25]:
print(even_arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


5.Create a 3x3 matrix with values ranging from 0 to 8

In [26]:
values_arr = np.arange(12)

matrix = values_arr.reshape((2,3,2))

In [27]:
print(matrix)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


6.Create a 3x3 identity matrix

In [28]:
matrix = np.eye(3)

In [29]:
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


7.Use NumPy to generate a random number between 0 and 1

In [30]:
rando = np.random.rand()

In [31]:
print(rando)

0.2823720686457962


8.Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [32]:
rand = np.random.randn(25)

In [33]:
print(rand)

[ 0.74553262 -2.05986111  1.21319731  0.67800115  1.05089455 -1.75941575
 -1.07038909 -0.27616284  0.98887531  0.54067342  2.16093905 -0.32116282
  0.43997184 -0.19437767  0.36614969  0.43038794  1.60771205  0.2772239
 -0.629688   -0.80370264 -1.32411836 -0.56738848  1.50068499  0.31089045
  1.02689601]


9.Create an array of 20 linearly spaced points between 0 and 1:

In [34]:
space = np.linspace(0, 1, 20)

In [35]:
print(space)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


10.Make a 432 matrix (NumPy array) containing linearly spaced integers between 100 and 1000.

In [57]:
linear = np.linspace(100, 1000, 432)

matrix = linear.reshape(4, 108)

In [58]:
print(matrix)

[[ 100.          102.08816705  104.17633411  106.26450116  108.35266821
   110.44083527  112.52900232  114.61716937  116.70533643  118.79350348
   120.88167053  122.96983759  125.05800464  127.14617169  129.23433875
   131.3225058   133.41067285  135.49883991  137.58700696  139.67517401
   141.76334107  143.85150812  145.93967517  148.02784223  150.11600928
   152.20417633  154.29234339  156.38051044  158.46867749  160.55684455
   162.6450116   164.73317865  166.82134571  168.90951276  170.99767981
   173.08584687  175.17401392  177.26218097  179.35034803  181.43851508
   183.52668213  185.61484919  187.70301624  189.79118329  191.87935035
   193.9675174   196.05568445  198.14385151  200.23201856  202.32018561
   204.40835267  206.49651972  208.58468677  210.67285383  212.76102088
   214.84918794  216.93735499  219.02552204  221.1136891   223.20185615
   225.2900232   227.37819026  229.46635731  231.55452436  233.64269142
   235.73085847  237.81902552  239.90719258  241.99535963  244.0

11.Print all columns except the first and the last in the above matrix.

In [38]:
integers = np.linspace(100, 1000, 432)

mat = integers.reshape(4, 108)

In [39]:
print(mat[:, 1:-1])

[[102.08816705 104.17633411 106.26450116 108.35266821 110.44083527
  112.52900232 114.61716937 116.70533643 118.79350348 120.88167053
  122.96983759 125.05800464 127.14617169 129.23433875 131.3225058
  133.41067285 135.49883991 137.58700696 139.67517401 141.76334107
  143.85150812 145.93967517 148.02784223 150.11600928 152.20417633
  154.29234339 156.38051044 158.46867749 160.55684455 162.6450116
  164.73317865 166.82134571 168.90951276 170.99767981 173.08584687
  175.17401392 177.26218097 179.35034803 181.43851508 183.52668213
  185.61484919 187.70301624 189.79118329 191.87935035 193.9675174
  196.05568445 198.14385151 200.23201856 202.32018561 204.40835267
  206.49651972 208.58468677 210.67285383 212.76102088 214.84918794
  216.93735499 219.02552204 221.1136891  223.20185615 225.2900232
  227.37819026 229.46635731 231.55452436 233.64269142 235.73085847
  237.81902552 239.90719258 241.99535963 244.08352668 246.17169374
  248.25986079 250.34802784 252.4361949  254.52436195 256.612529
 

12.Find the median of the above-generated 432 matrix along the columns

In [62]:
line = np.linspace(100, 1000, 432)

matr = line.reshape(4, 108)

median = np.median(matr, axis=0)

In [63]:
print(median)

[438.28306265 440.3712297  442.45939675 444.54756381 446.63573086
 448.72389791 450.81206497 452.90023202 454.98839907 457.07656613
 459.16473318 461.25290023 463.34106729 465.42923434 467.51740139
 469.60556845 471.6937355  473.78190255 475.87006961 477.95823666
 480.04640371 482.13457077 484.22273782 486.31090487 488.39907193
 490.48723898 492.57540603 494.66357309 496.75174014 498.83990719
 500.92807425 503.0162413  505.10440835 507.19257541 509.28074246
 511.36890951 513.45707657 515.54524362 517.63341067 519.72157773
 521.80974478 523.89791183 525.98607889 528.07424594 530.16241299
 532.25058005 534.3387471  536.42691415 538.51508121 540.60324826
 542.69141531 544.77958237 546.86774942 548.95591647 551.04408353
 553.13225058 555.22041763 557.30858469 559.39675174 561.48491879
 563.57308585 565.6612529  567.74941995 569.83758701 571.92575406
 574.01392111 576.10208817 578.19025522 580.27842227 582.36658933
 584.45475638 586.54292343 588.63109049 590.71925754 592.80742459
 594.89559

13.Make another 2*4 matrix containing only elements from the above matrix, which are between 400 and 750.

In [65]:
line = np.linspace(100, 1000, 432)

matrix = line.reshape(4, 108)

mask = (matrix >= 400) & (matrix <= 750)

filtered = matrix[mask].reshape(2*4, 21)

In [66]:
print(filtered)

[[400.69605568 402.78422274 404.87238979 406.96055684 409.0487239
  411.13689095 413.225058   415.31322506 417.40139211 419.48955916
  421.57772622 423.66589327 425.75406032 427.84222738 429.93039443
  432.01856148 434.10672854 436.19489559 438.28306265 440.3712297
  442.45939675]
 [444.54756381 446.63573086 448.72389791 450.81206497 452.90023202
  454.98839907 457.07656613 459.16473318 461.25290023 463.34106729
  465.42923434 467.51740139 469.60556845 471.6937355  473.78190255
  475.87006961 477.95823666 480.04640371 482.13457077 484.22273782
  486.31090487]
 [488.39907193 490.48723898 492.57540603 494.66357309 496.75174014
  498.83990719 500.92807425 503.0162413  505.10440835 507.19257541
  509.28074246 511.36890951 513.45707657 515.54524362 517.63341067
  519.72157773 521.80974478 523.89791183 525.98607889 528.07424594
  530.16241299]
 [532.25058005 534.3387471  536.42691415 538.51508121 540.60324826
  542.69141531 544.77958237 546.86774942 548.95591647 551.04408353
  553.13225058 5

14.Print the sum of all the rows in the above 2*4 matrix. (Note: Kindly print only, do not overwrite the matrix.)

In [44]:
line = np.linspace(100, 1000, 432)

matrix = line.reshape(4, 108)

mask = (matrix >= 400) & (matrix <= 750)

filter = matrix[mask].reshape(2*4, 21)

In [45]:
print(np.sum(filter, axis=1))

[ 8853.13225058  9774.01392111 10694.89559165 11615.77726218
 12536.65893271 13457.54060325 14378.42227378 15299.30394432]


15.Create a 4*5 array with 1 on the border and 0 inside.

In [46]:
arr = np.zeros((4, 5))

arr[0, :] = 1
arr[-1, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1


In [47]:
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
