**1. Generate a random normally distributed 1D array of size 100 with values between 1 and 10. Compute the mean and standard deviation of the array.**

In [33]:
import numpy as np

arr=np.random.normal(size=100)

arr=np.clip(arr,1,10)

mean=np.mean(arr)
std=np.std(arr)

print("Mean of the array:",mean)
print("Deviation of the array:",std)

Mean of the array: 1.0872480961800204
Deviation of the array: 0.2986504942028962


**2. Create a 5x5 matrix with random integers. Extract the diagonal elements and find their sum.**

In [34]:
matrix=np.random.randint(1,100,size=(5,5))
print("Matrix is:", matrix)

diagonal = np.diag(matrix)
print("\nDiagonal elements:",diagonal)

sum=np.sum(diagonal)
print("\nDiagonal elements sum:",sum)

Matrix is: [[98 61 33 46 80]
 [78 34 27 17 79]
 [12 77 43 64 88]
 [85 43 99 64 15]
 [42 72 53 58 81]]

Diagonal elements: [98 34 43 64 81]

Diagonal elements sum: 320


3. **Create a class named `Person` with properties `name` and `age`. Include a method `greet` that prints a simple greeting using the person's name.**

- Create an instance of the `Person` class named `person1` with the name "John" and age 25.
- Call the greet method on `person1` to display their greetings.

In [35]:
class Person:
  def __init__(self,name,age):
    self.name=name
    self.age=age

  def greet(self):
    print(f"Person name is {self.name}")

person1=Person("John",25)
person1.greet()

Person name is John


4. **Design a class `Employee` with private properties `name` and `salary`. Implement a method `get_salary` that retrieves the salary. Ensure that the salary is not directly modifiable from outside the class.**

- Create an instance of the `Employee` class named `employee1` with the name "John" and a salary of $50,000.
- Use the `get_salary` method to retrieve and display the salary of `employee1`.
- Attempt to modify the salary of `employee1` directly from outside the class and observe the result.

In [36]:
class Employee:
  def __init__(self,name,salary):
    self.__name=name
    self.__salary=salary

  def get_salary(self):
    return self.__salary

employee1=Employee("John",50000)
print("Employee salary is:",employee1.get_salary())

employee1.__salary=250000
print("\nModified salary is:",employee1.get_salary())

Employee salary is: 50000

Modified salary is: 50000


5. **You're working on a system for tracking online orders. Create a class `Order` with properties `order_id`, `customer_name`, and `total_amount`. Include a method `calculate_discount` that returns a discounted total if the total_amount is greater than $50.**

- Create an instance of the `Order` class named `order1` with an order ID of "12345", customer name "Alice," and a total amount of $100.
- Use the `calculate_discount` method to retrieve and display the `discounted total` for `order1`.

In [37]:
class Order:
  def __init__(self,order_id,customer_name,total_amount):
    self.order_id=order_id
    self.customer_name=customer_name
    self.total_amount=total_amount

  def calculate_discount(self):
    if self.total_amount > 50:
      discount=self.total_amount * 0.1
      total_dis = self.total_amount - discount
      return total_dis

    else:
      return self.total_amount

order1 = Order("12345","Alice",100)

discounted_total=order1.calculate_discount()
print("Total discount in oroder is:", discounted_total)


Total discount in oroder is: 90.0


6. **Create a class `BankAccount` with private properties `balance` and `account_number`. Include methods `deposit` and `withdraw` that modify the balance.**

- Create an instance of the `BankAccount` class named `account1` with an account number "123456" and an initial balance of $1000.

- Use the `deposit` method to add \\$500 to the balance of `account1`. Check the result.
- Use the `withdraw` method to deduct $200 from the balance of `account1`. Check the result.

In [38]:
class BankAccount:
  def __init__(self,account_number,balance):
    self.__balance=balance
    self.__account_number=account_number

  def deposit(self,n):
    self.__balance+=n

  def withdraw(self,n):
    if self.__balance>=n:
      self.__balance-=n
    else:
      print("Insufficient fund")

  def get_balance(self):
    return self.__balance

account1=BankAccount("123456",1000)
account1.deposit(500)
print("Balance after deposit:",account1.get_balance())

account1.withdraw(200)
print("After withdraw balance is:",account1.get_balance())


Balance after deposit: 1500
After withdraw balance is: 1300


7. Create a class named `CustomMath` with a method `perform_operations`. This method should take any number of numeric values as positional arguments (`*args`) and an operation specified as a keyword argument (`operation`). The operations supported are 'add', 'subtract', 'multiply', and 'divide'. Implement the necessary logic to perform the specified operation on the given numeric values and print the result.

Example outputs
- `custom_math_instance.perform_operations('add', 5, 3, 2, 6, 5, 8,100)  # Output: Result of add operation: 129`
- `custom_math_instance.perform_operations('subtract', 10, 2, 3)  # Output: Result of subtract operation: 5`
- `custom_math_instance.perform_operations('multiply', 2, 4)  # Output: Result of multiply operation: 8`
- `custom_math_instance.perform_operations('divide', 100,45)  # Output: Result of divide operation: 2.2222222222222223`




In [39]:
class CustomMath:
  def perform_operations(self, operation, *args):
    result = None
    if operation == "add":
      result = np.sum(args)
    elif operation == "subtract":
      result = args[0]
      for num in args[1:]:
        result -=num

    elif operation == "multiply":
      result = 1
      for num in args:
        result *=num
    elif operation == "divide":
      result = args[0]
      for num in args[1:]:
        result /=num

    else:
      print("Invalid Operation")
      return
    print(f"Result of {operation} is", result)

custom_math_instance=CustomMath()

custom_math_instance.perform_operations('add', 5, 3, 2, 6, 5, 8,100)
custom_math_instance.perform_operations('subtract', 10, 2, 3)
custom_math_instance.perform_operations('multiply', 2, 4)
custom_math_instance.perform_operations('divide', 100,45)

Result of add is 129
Result of subtract is 5
Result of multiply is 8
Result of divide is 2.2222222222222223


8. Create a class representing a `shopping_cart`. Include methods for `add_items` and `remove_items`, and `calculate_total_price`. Hint: Use a dictionary to store items and their quantities in the shopping cart, and implement methods to add items, remove items to the dictionary.
