1. Create a 2D array representing a chessboard with 0s and 1s. Use advanced indexing to extract the positions of all 1s (representing chess pieces) on the board.

In [5]:
import numpy as np

chessboard = np.zeros((8, 8), dtype=int)

chessboard[1::2, ::2] = 1
chessboard[::2, 1::2] = 1

print("Chessboard:")
print(chessboard)

Chessboard:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [6]:
positions_of_ones = np.argwhere(chessboard == 1)

print("Positions of all 1s:")
print(positions_of_ones)

Positions of all 1s:
[[0 1]
 [0 3]
 [0 5]
 [0 7]
 [1 0]
 [1 2]
 [1 4]
 [1 6]
 [2 1]
 [2 3]
 [2 5]
 [2 7]
 [3 0]
 [3 2]
 [3 4]
 [3 6]
 [4 1]
 [4 3]
 [4 5]
 [4 7]
 [5 0]
 [5 2]
 [5 4]
 [5 6]
 [6 1]
 [6 3]
 [6 5]
 [6 7]
 [7 0]
 [7 2]
 [7 4]
 [7 6]]


2.i. **arr1:** Create a 1D array with values from 1 to 12.

2.ii. **arr2:** Create a 2D array with shape (3, 4) containing random integers.

Reshape **arr1** into a 3x4 matrix. Print the reshaped array.
Resize **arr2** to have 5 columns. Print the resized array.


In [24]:
import numpy as np

arr1 = np.arange(1, 13)

arr2 = np.random.randint(1, 100, size=(3, 4))

reshaped_arr1 = np.reshape(arr1, (3, 4))

print("Reshaped arr1:")
print(reshaped_arr1)

Reshaped arr1:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
resized_arr2 = np.resize(arr2, (3, 5))

print("\nResized arr2:")
print(resized_arr2)


Resized arr2:
[[ 6 75  7 78 26]
 [69 92 92 40 16]
 [73 80  6 75  7]]


3.Design a class **BankAccount** with a constructor that initializes the **account_number** and **balance**. Include methods **deposit** and **withdraw** to modify the balance.      
Create an instance of the BankAccount class named account1 with an account number "123456" and an initial balance of $1000.     

Use the deposit method to add $500 to the balance of account1.

Use the withdraw method to deduct $200 from the balance of account1.

In [9]:
class BankAccount:
    def __init__(self, account_number, balance):
        self.account_number = account_number
        self.balance = balance

    def deposit(self, amount):
        self.balance += amount

    def withdraw(self, amount):
        if self.balance >= amount:
            self.balance -= amount
        else:
            print("Insufficient funds")

In [10]:
account1 = BankAccount("123456", 1000)
account1.deposit(500)
account1.withdraw(200)

print("Account balance after deposit and withdrawal:", account1.balance)

Account balance after deposit and withdrawal: 1300


4.Design a class Building with properties name and floors. Create a derived class OfficeBuilding that includes an additional property occupancy_rate.

Create an instance of the Building class named building1 with the name
"Residential Tower" and 20 floors.

Create an instance of the OfficeBuilding class named building2 with the name "Corporate Plaza," 15 floors, and an occupancy rate of 85%.




In [11]:
class Building:
    def __init__(self, name, floors):
        self.name = name
        self.floors = floors

class OfficeBuilding(Building):
    def __init__(self, name, floors, occupancy_rate):
        super().__init__(name, floors)
        self.occupancy_rate = occupancy_rate

In [14]:
building1 = Building("Residential Tower", 20)

building2 = OfficeBuilding("Corporate Plaza", 15, 0.85)

print("Details of building1:")
print("Name:", building1.name)
print("Floors:", building1.floors)

print("\nDetails of building2:")
print("Name:", building2.name)
print("Floors:", building2.floors)
print("Occupancy Rate:", building2.occupancy_rate)

Details of building1:
Name: Residential Tower
Floors: 20

Details of building2:
Name: Corporate Plaza
Floors: 15
Occupancy Rate: 0.85


5.You're developing a game. Design a class Character with a method attack. Create derived classes Player and Enemy that override the attack method to define player and enemy attacks.

Create an instance of the Player class named player1 and an instance of the Enemy class named enemy1.

Call the attack method for both player1 and enemy1 to see their respective attacks.

In [17]:
class Character:
    def attack(self):
        pass

class Player(Character):
    def attack(self):
        return "Player attacks with a sword!"

class Enemy(Character):
    def attack(self):
        return "Enemy attacks with claws!"

In [18]:
player1 = Player()

enemy1 = Enemy()

print("Player1 attack:", player1.attack())
print("Enemy1 attack:", enemy1.attack())

Player1 attack: Player attacks with a sword!
Enemy1 attack: Enemy attacks with claws!


6.You are tasked with designing a class hierarchy for managing a fleet of vehicles. Create a base class Vehicle with public properties make and model, and a private property year. Implement a method get_year in the Vehicle class to retrieve the private year property. Now, extend the Vehicle class to create a derived class ElectricVehicle. The ElectricVehicle class should include properties battery_capacity and charging_time.

*   Create an instance of the Vehicle class named vehicle1 with make "Toyota,"model "Camry," and year 2022.
*   Use the get_year method to retrieve and display the year of vehicle1.
Create an instance of the ElectricVehicle class named ev1 with make "Tesla," model "Model S," year 2023, battery capacity of 75 kWh, and charging time of 4 hours.
* Use the get_year method to retrieve and display the year of ev1.
Display the battery capacity and charging time of ev1.


In [19]:
class Vehicle:
    def __init__(self, make, model, year):
        self.make = make
        self.model = model
        self.__year = year

    def get_year(self):
        return self.__year

class ElectricVehicle(Vehicle):
    def __init__(self, make, model, year, battery_capacity, charging_time):
        super().__init__(make, model, year)
        self.battery_capacity = battery_capacity
        self.charging_time = charging_time

In [20]:
vehicle1 = Vehicle("Toyota", "Camry", 2022)

print("Year of vehicle1:", vehicle1.get_year())

ev1 = ElectricVehicle("Tesla", "Model S", 2023, 75, "4 hours")

print("Year of ev1:", ev1.get_year())

print("Battery Capacity of ev1:", ev1.battery_capacity, "kWh")
print("Charging Time of ev1:", ev1.charging_time)

Year of vehicle1: 2022
Year of ev1: 2023
Battery Capacity of ev1: 75 kWh
Charging Time of ev1: 4 hours
